name: INFORMATION-WORKFLOW
on:
  push:
    branches:
      - "main"
    paths:
      - "**.js"
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: PRINT-CONTEXT-STEP
        run: echo "${{toJSON(github)}}"
